# Generated by Django 5.2.5 on 2026-08-09 13:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarePlanVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('summary', models.TextField(blank=True)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('uncertainties', models.JSONField(blank=True, default=list)),
                ('source_type', models.CharField(default='ai', max_length=20)),
                ('model_name', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('pending', 'Väntar på granskning'), ('active', 'Aktiv'), ('superseded', 'Ersatt'), ('rejected', 'Avvisad'), ('failed', 'Misslyckad')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='GardenItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('canonical_name', models.CharField(blank=True, max_length=120)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('kind', models.CharField(choices=[('individual', 'Enskild växt'), ('group', 'Grupp'), ('bed', 'Odlingsbädd')], default='individual', max_length=20)),
                ('cultivar', models.CharField(blank=True, max_length=120)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('age_stage', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=160)),
                ('notes', models.TextField(blank=True)),
                ('icon', models.CharField(default='leaf', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GardenSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garden_name', models.CharField(default='Vår trädgård', max_length=120)),
                ('city', models.CharField(default='Karlskrona', max_length=80)),
                ('cultivation_zone', models.CharField(default='1', max_length=20)),
                ('exposure', models.CharField(default='Skyddat, kustnära läge', max_length=160)),
                ('timezone', models.CharField(default='Europe/Stockholm', max_length=64)),
                ('monthly_digest_day', models.PositiveSmallIntegerField(default=1)),
                ('reminder_weekday', models.PositiveSmallIntegerField(default=6)),
                ('reminder_hour', models.PositiveSmallIntegerField(default=9)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(max_length=1000, unique=True)),
                ('p256dh', models.CharField(max_length=500)),
                ('auth', models.CharField(max_length=500)),
                ('device_name', models.CharField(blank=True, max_length=120)),
                ('monthly_digest', models.BooleanField(default=False)),
                ('task_reminders', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CareRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('instructions', models.TextField(blank=True)),
                ('cadence', models.CharField(choices=[('one_off', 'Engångsuppgift'), ('seasonal', 'En gång per säsong'), ('monthly', 'Varje månad i fönstret')], default='seasonal', max_length=20)),
                ('start_month', models.PositiveSmallIntegerField(default=1)),
                ('end_month', models.PositiveSmallIntegerField(default=1)),
                ('one_off_date', models.DateField(blank=True, null=True)),
                ('conditional', models.BooleanField(default=False)),
                ('confidence', models.CharField(choices=[('high', 'Hög'), ('medium', 'Medel'), ('low', 'Låg')], default='medium', max_length=12)),
                ('source_urls', models.JSONField(blank=True, default=list)),
                ('source_validated', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('reminder_day', models.PositiveSmallIntegerField(default=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rules', to='garden.careplanversion')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_rules', to='garden.gardenitem')),
            ],
        ),
        migrations.AddField(
            model_name='careplanversion',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='garden.gardenitem'),
        ),
        migrations.CreateModel(
            name='ResearchProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Väntar'), ('approved', 'Godkänd'), ('rejected', 'Avvisad'), ('failed', 'Misslyckad')], default='pending', max_length=20)),
                ('response_id', models.CharField(blank=True, max_length=120)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='garden.gardenitem')),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proposal', to='garden.careplanversion')),
            ],
        ),
        migrations.CreateModel(
            name='SourceReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('url', models.URLField(max_length=1000)),
                ('domain', models.CharField(blank=True, max_length=160)),
                ('summary', models.TextField(blank=True)),
                ('accessed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_swedish_authority', models.BooleanField(default=False)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='garden.careplanversion')),
            ],
        ),
        migrations.CreateModel(
            name='TaskOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('instructions', models.TextField(blank=True)),
                ('occurrence_key', models.CharField(max_length=220, unique=True)),
                ('season_year', models.PositiveIntegerField()),
                ('occurrence_month', models.PositiveSmallIntegerField()),
                ('window_start', models.DateField()),
                ('window_end', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Öppen'), ('completed', 'Klar'), ('skipped', 'Hoppad över')], default='pending', max_length=20)),
                ('manual', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('skipped_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='garden.gardenitem')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='garden.carerule')),
            ],
            options={
                'ordering': ['window_end', 'window_start', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ReminderDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=30)),
                ('delivery_key', models.CharField(max_length=240, unique=True)),
                ('scheduled_for', models.DateTimeField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('error', models.TextField(blank=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='garden.pushsubscription')),
                ('occurrence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='garden.taskoccurrence')),
            ],
        ),
        migrations.AddConstraint(
            model_name='careplanversion',
            constraint=models.UniqueConstraint(fields=('item', 'version'), name='unique_plan_version'),
        ),
        migrations.AddConstraint(
            model_name='sourcereference',
            constraint=models.UniqueConstraint(fields=('plan', 'url'), name='unique_plan_source'),
        ),
        migrations.AddIndex(
            model_name='taskoccurrence',
            index=models.Index(fields=['status', 'window_start', 'window_end'], name='garden_task_status_b5bf16_idx'),
        ),
        migrations.AddIndex(
            model_name='taskoccurrence',
            index=models.Index(fields=['item', 'occurrence_month'], name='garden_task_item_id_db49c0_idx'),
        ),
    ]
