# Generated by Django 5.2.5 on 2026-08-09 14:35

from django.db import migrations, models
from django.utils import timezone


def supersede_older_pending_proposals(apps, schema_editor):
    ResearchProposal = apps.get_model('garden', 'ResearchProposal')
    CarePlanVersion = apps.get_model('garden', 'CarePlanVersion')
    reviewed_at = timezone.now()
    item_ids = ResearchProposal.objects.filter(status='pending').values_list('item_id', flat=True).distinct()
    for item_id in item_ids:
        pending = list(
            ResearchProposal.objects.filter(item_id=item_id, status='pending')
            .order_by('-plan__version', '-id')
        )
        older = pending[1:]
        if not older:
            continue
        proposal_ids = [proposal.pk for proposal in older]
        plan_ids = [proposal.plan_id for proposal in older]
        ResearchProposal.objects.filter(pk__in=proposal_ids).update(status='superseded', reviewed_at=reviewed_at)
        CarePlanVersion.objects.filter(pk__in=plan_ids).update(status='superseded', reviewed_at=reviewed_at)


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchproposal',
            name='status',
            field=models.CharField(choices=[('pending', 'Väntar'), ('approved', 'Godkänd'), ('rejected', 'Avvisad'), ('superseded', 'Ersatt'), ('failed', 'Misslyckad')], default='pending', max_length=20),
        ),
        migrations.RunPython(supersede_older_pending_proposals, migrations.RunPython.noop),
    ]
