# Generated by Django 5.2.5 on 2026-08-11 05:56

import django.db.models.deletion
from django.db import migrations, models


WORK_CATEGORIES = (
    "Vattna", "Beskära och binda upp", "Kontrollera", "Gödsla",
    "Jord och ogräs", "Skörda", "Övrigt",
)
REANALYSIS_MARKER = "Ersätts med det nya arbetsrundeschemat."


def normalize(value, fallback_text=""):
    if value in WORK_CATEGORIES:
        return value
    text = f"{value or ''} {fallback_text or ''}".casefold()
    mappings = (
        ("Vattna", ("vatt", "bevatt")),
        ("Beskära och binda upp", ("beskär", "gallra", "bind", "stötta", "klipp", "skott")),
        ("Kontrollera", ("kontroll", "inspek", "övervaka", "håll utkik", "bedöm", "följ upp", "sjuk", "skadedjur")),
        ("Gödsla", ("göd", "näring", "kompostte", "npk")),
        ("Jord och ogräs", ("jord", "ogräs", "luckra", "täck", "mulch", "kompost")),
        ("Skörda", ("skörd", "plocka", "frukt", "bär")),
    )
    for category, needles in mappings:
        if any(needle in text for needle in needles):
            return category
    return "Övrigt"


def normalize_active_work(apps, schema_editor):
    CareRule = apps.get_model("garden", "CareRule")
    ResearchProposal = apps.get_model("garden", "ResearchProposal")
    TaskOccurrence = apps.get_model("garden", "TaskOccurrence")
    for rule in CareRule.objects.filter(active=True):
        rule.category = normalize(rule.category, f"{rule.title} {rule.instructions}")
        rule.save(update_fields=["category"])
    for task in TaskOccurrence.objects.filter(status="pending").select_related("rule"):
        source_category = task.rule.category if task.rule_id else ""
        task.category = normalize(source_category, f"{task.title} {task.instructions}")
        task.save(update_fields=["category"])
    ResearchProposal.objects.filter(status="pending").update(error=REANALYSIS_MARKER)


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0003_archive_pre_activation_backlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='GardenArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='taskoccurrence',
            name='category',
            field=models.CharField(choices=[('Vattna', 'Vattna'), ('Beskära och binda upp', 'Beskära och binda upp'), ('Kontrollera', 'Kontrollera'), ('Gödsla', 'Gödsla'), ('Jord och ogräs', 'Jord och ogräs'), ('Skörda', 'Skörda'), ('Övrigt', 'Övrigt')], default='Övrigt', max_length=80),
        ),
        migrations.AlterField(
            model_name='carerule',
            name='category',
            field=models.CharField(choices=[('Vattna', 'Vattna'), ('Beskära och binda upp', 'Beskära och binda upp'), ('Kontrollera', 'Kontrollera'), ('Gödsla', 'Gödsla'), ('Jord och ogräs', 'Jord och ogräs'), ('Skörda', 'Skörda'), ('Övrigt', 'Övrigt')], default='Övrigt', max_length=80),
        ),
        migrations.AddField(
            model_name='gardenitem',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='garden.gardenarea'),
        ),
        migrations.RunPython(normalize_active_work, migrations.RunPython.noop),
    ]
