# Generated by Django 5.2.5 on 2026-09-12 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0007_repair_work_categories_and_to_donts'),
    ]

    operations = [
        migrations.AddField(
            model_name='careplanversion',
            name='effective_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careplanversion',
            name='research_context',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='carerule',
            name='advice_kind',
            field=models.CharField(choices=[('planned', 'Planerat arbete'), ('on_demand', 'Vid behov'), ('general', 'Allmänt råd'), ('review', 'Kräver granskning')], default='planned', max_length=20),
        ),
        migrations.AddField(
            model_name='carerule',
            name='evidence_conflict',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='carerule',
            name='need_condition',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='carerule',
            name='one_off_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carerule',
            name='relevance_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='researchproposal',
            name='review_receipt',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='taskoccurrence',
            name='archive_reason',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='taskoccurrence',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskoccurrence',
            name='identity_slot',
            field=models.CharField(blank=True, max_length=240, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='taskoccurrence',
            name='status',
            field=models.CharField(choices=[('pending', 'Öppen'), ('completed', 'Klar'), ('skipped', 'Hoppad över'), ('archived', 'Arkiverad')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='WorkIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_key', models.CharField(max_length=100)),
                ('scope', models.CharField(default='hela-växten', max_length=160)),
                ('excluded_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='garden.gardenitem')),
            ],
        ),
        migrations.AddField(
            model_name='carerule',
            name='work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rules', to='garden.workidentity'),
        ),
        migrations.AddField(
            model_name='taskoccurrence',
            name='work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='occurrences', to='garden.workidentity'),
        ),
        migrations.AddConstraint(
            model_name='workidentity',
            constraint=models.UniqueConstraint(fields=('item', 'action_key', 'scope'), name='unique_item_work_scope'),
        ),
    ]
