# Generated by Django 5.2.5 on 2026-09-25 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0010_workidentity_merged_into_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Garden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GardenMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Ägare'), ('member', 'Medlem')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('garden', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='garden.garden')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='garden_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('garden', 'user'), name='unique_garden_user'), models.CheckConstraint(condition=models.Q(('role__in', ['owner', 'member'])), name='valid_garden_member_role')],
            },
        ),
    ]
