# Generated by Django 5.2.17 on 2026-09-26 05:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0012_idempotencyrecord_garden_public_id_garden_version_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('membership_pk', models.PositiveBigIntegerField()),
                ('kind', models.CharField(choices=[('research', 'Research'), ('reminder', 'Reminder')], max_length=16)),
                ('key', models.CharField(max_length=240)),
                ('fingerprint', models.CharField(max_length=64)),
                ('state', models.CharField(default='queued', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('available_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lease_until', models.DateTimeField(null=True)),
                ('token', models.UUIDField(null=True)),
                ('reason', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('delivery', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='garden.reminderdelivery')),
                ('garden', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='garden.garden')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='garden.gardenitem')),
                ('proposal', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='garden.researchproposal')),
            ],
        ),
        migrations.CreateModel(
            name='JobAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('token', models.UUIDField(unique=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(null=True)),
                ('outcome', models.CharField(default='running', max_length=32)),
                ('reason', models.CharField(blank=True, max_length=80)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='garden.backgroundjob')),
            ],
        ),
        migrations.AddIndex(
            model_name='backgroundjob',
            index=models.Index(fields=['state', 'available_at'], name='garden_back_state_6e418b_idx'),
        ),
        migrations.AddConstraint(
            model_name='backgroundjob',
            constraint=models.UniqueConstraint(fields=('garden', 'actor', 'kind', 'key'), name='unique_job_request'),
        ),
        migrations.AddConstraint(
            model_name='backgroundjob',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'research'), ('state__in', ['queued', 'running', 'sending', 'uncertain'])), fields=('item',), name='one_active_research_job'),
        ),
        migrations.AddConstraint(
            model_name='backgroundjob',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ['queued', 'running', 'sending', 'succeeded', 'failed', 'cancelled', 'uncertain'])), name='valid_job_state'),
        ),
        migrations.AddConstraint(
            model_name='backgroundjob',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('delivery__isnull', True), ('item__isnull', False), ('kind', 'research')), models.Q(('delivery__isnull', False), ('item__isnull', True), ('kind', 'reminder')), _connector='OR'), name='valid_job_target'),
        ),
        migrations.AddConstraint(
            model_name='jobattempt',
            constraint=models.UniqueConstraint(fields=('job', 'number'), name='unique_job_attempt'),
        ),
    ]
