# Generated by Django 5.2.17 on 2026-09-26 08:59

import django.core.serializers.json
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0013_backgroundjob_jobattempt_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('confirmed_not_sent', 'Confirmed not sent'), ('confirmed_received', 'Confirmed received')], max_length=32)),
                ('evidence', models.CharField(max_length=500)),
                ('snapshot_hash', models.CharField(max_length=64)),
                ('snapshot', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='backgroundjob',
            name='valid_job_state',
        ),
        migrations.AddConstraint(
            model_name='backgroundjob',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ['queued', 'running', 'sending', 'succeeded', 'failed', 'cancelled', 'uncertain', 'reconciled'])), name='valid_job_state'),
        ),
        migrations.AddField(
            model_name='jobreconciliation',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation', to='garden.backgroundjob'),
        ),
        migrations.AddField(
            model_name='jobreconciliation',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='jobreconciliation',
            constraint=models.CheckConstraint(condition=models.Q(('decision__in', ['confirmed_not_sent', 'confirmed_received'])), name='valid_job_reconciliation'),
        ),
    ]
