# Generated by Django 5.2.17 on 2026-09-29 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0014_job_reconciliation'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushsubscription',
            name='native_membership_pk',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pushsubscription',
            name='native_token',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='pushsubscription',
            name='provider',
            field=models.CharField(choices=[('web', 'Web Push'), ('expo', 'Expo Push')], default='web', max_length=12),
        ),
    ]
