# Generated by Django 5.2.17 on 2026-09-29 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_mobileloginattempt_mobilesession'),
        ('garden', '0015_pushsubscription_native_membership_pk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushsubscription',
            name='native_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.mobilesession'),
        ),
    ]
